# Generated by Django 6.0 on 2026-04-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='posts_per_day',
            field=models.IntegerField(default=-1, help_text='Max posts per day. -1 = unlimited.'),
        ),
        migrations.AddField(
            model_name='postusage',
            name='daily_posts_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postusage',
            name='last_post_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
