# Generated by Django 6.0 on 2026-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_posts_per_day_postusage_daily_posts_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='posts_per_month',
        ),
        migrations.AddField(
            model_name='plan',
            name='posts_limit',
            field=models.IntegerField(default=30, help_text='Total posts allowed in the period (e.g., 7-day trial or 1 month). -1 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='posts_per_day',
            field=models.IntegerField(default=3, help_text='Max posts per day. -1 = unlimited.'),
        ),
    ]
