# Generated by Django 6.0 on 2026-04-02 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='platform_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='token_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('state', models.CharField(max_length=255, unique=True)),
                ('redirect_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'state'], name='core_oauths_platfor_d3ae89_idx'), models.Index(fields=['expires_at'], name='core_oauths_expires_e5c973_idx')],
            },
        ),
    ]
