# Generated by Django 6.0 on 2026-04-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialaccount_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='callback_uri',
            field=models.URLField(blank=True, help_text='The exact callback URI sent to the provider', max_length=500),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='The frontend URL to redirect to after success/error'),
        ),
    ]
