# Generated by Django 6.0 on 2026-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_oauthstate_callback_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='code_verifier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
