# Generated by Django 6.0 on 2026-04-02 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_oauthstate_code_verifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='callback_uri',
            field=models.URLField(blank=True, help_text='Exact callback URI sent to provider', max_length=500),
        ),
        migrations.AlterField(
            model_name='oauthstate',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Frontend URL to redirect to after success/error'),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['used_at'], name='core_oauths_used_at_0c30fb_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['expires_at'], name='core_social_expires_58b51d_idx'),
        ),
    ]
