# Generated by Django 6.0 on 2026-04-15 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oauthstate_used_at_alter_oauthstate_callback_uri_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Platform-specific content tweaks'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, help_text='Direct media upload', null=True, upload_to='post_media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('published', 'Published'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PostingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'time'],
                'unique_together': {('user', 'day_of_week', 'time')},
            },
        ),
    ]
