# Generated by Django 6.0 on 2026-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_content_overrides_post_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for multi-image posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, help_text='Direct media upload (single file, legacy)', null=True, upload_to='post_media/'),
        ),
    ]
