# Generated by Django 6.0 on 2026-04-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_images_alter_post_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, help_text='External video URL', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded video file', null=True, upload_to='post_videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, help_text='Single image URL (legacy)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, help_text='Single uploaded image file (legacy)', null=True, upload_to='post_media/'),
        ),
    ]
