# Generated by Django 6.0 on 2026-04-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_video_post_video_file_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platform_options',
            field=models.JSONField(blank=True, default=dict, help_text='Per-platform posting options e.g. Instagram post type'),
        ),
    ]
