# Generated by Django 6.0 on 2026-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_oauthstate_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform_options',
            field=models.JSONField(blank=True, default=dict, help_text='Per-platform posting options e.g. Instagram post type, YouTube privacy'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
