# Generated by Django 6.0 on 2026-04-21 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_oauthstate_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='unique_user_platform_account',
        ),
        migrations.AddField(
            model_name='post',
            name='target_accounts',
            field=models.JSONField(default=list, help_text='List of SocialAccount IDs to post to'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='account_label',
            field=models.CharField(blank=True, help_text='Display name shown in UI (pulled from platform during OAuth)', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-account content overrides keyed by social_account.id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform_options',
            field=models.JSONField(blank=True, default=dict, help_text="Per-account posting options keyed by account_id e.g. {'instagram_post_type': 'reel'}"),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform_results',
            field=models.JSONField(blank=True, default=dict, help_text='Results keyed by social_account.id (str)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='platforms',
            field=models.JSONField(default=list, help_text='Legacy: list of platform names. Use target_accounts instead.'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'account_id'), name='unique_user_platform_account_id'),
        ),
    ]
