# Generated by Django 6.0.4 on 2026-06-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_oauthstate_login_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash-based key to prevent duplicate post submissions (user_id+content+accounts+time)",
                max_length=64,
            ),
        ),
    ]
